# Generated by Django 4.2.1 on 2023-05-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api',
        ),
    ]
